<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>7.3</LangVersion>
    <Nullable>disable</Nullable>
    <AssemblyName>serialctl</AssemblyName>
    <RootNamespace>SerialCtl.Win7</RootNamespace>
    <ApplicationIcon />
    <Platforms>AnyCPU</Platforms>
    <Prefer32Bit>false</Prefer32Bit>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SSH.NET" Version="2026.0.0" />
  </ItemGroup>
</Project>
